apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hmseWebserver.airflowSecretName }}
type: Opaque
stringData:
  {{- with (index .Values.airflow.airflow.users 0)}}
  airflow_user: {{ .username }}
  airflow_password: {{ .password }}
  {{- end }}
