{{- with .Values.hmseWebserver.s3.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  endpoint: {{ .endpoint }}
  access_key: {{ .accessKey }}
  secret_key: {{ .secretKey }}
{{- end -}}
