apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmse-k8s-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmse-k8s-webserver
  template:
    metadata:
      labels:
        app: hmse-k8s-webserver
    spec:
      containers:
      - name: hmse-k8s-webserver
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HMSE_URL_PREFIX
          value: {{ .Values.ingress.prefix }}
        - name: MINIO_REGION
          value: {{ .Values.s3.region }}
        - name: S3_TYPE
          value: {{ .Values.s3.interface }}
        - name: HMSE_MINIO_ROOT_BUCKET
          value: {{ .Values.s3.bucket }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret.name }}
              key: secret_key
              optional: false
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret.name }}
              key: access_key
              optional: false
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.secret.name }}
              key: endpoint
              optional: false
        - name: AIRFLOW_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.airflowSecretName }}
              key: airflow_user
              optional: false
        - name: AIRFLOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.airflowSecretName }}
              key: airflow_password
              optional: false
        - name: AIRFLOW_API_ENDPOINT
          value: {{ printf "%s-web.%s.svc.cluster.local:8080" (.Release.Name) (.Release.Namespace) }}/api/v1
