apiVersion: v2
name: hmse
description: Umbrella chart for running a HMSE workflow
type: application
version: 1.2.0
appVersion: "1.2.0"

dependencies:
  - name: airflow
    repository: https://airflow-helm.github.io/charts
    version: 8.7.0
  - name: hmseWebserver
    repository: file://charts/hmseWebserver
    version: 1.2.0

