apiVersion: v1
entries:
  hmse:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-05-04T10:55:28.682150606Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 1.2.0
    description: Umbrella chart for running a HMSE workflow
    digest: 22e2c8af71945ff8e1eee9a843b5a6be58381b9fcde37a176227bc4d60ba83f3
    name: hmse
    type: application
    urls:
    - hmse-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-04T10:55:28.671287839Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 1.0.0
    description: Umbrella chart for running a HMSE workflow
    digest: 0df0cedf797cbb88f07db4242e8e6b2e8576f739cc0d0a390356dcceb5716b6d
    name: hmse
    type: application
    urls:
    - hmse-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2026-05-04T10:55:28.660139475Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 0.1.0
    description: Umbrella chart for running a HMSE workflow
    digest: a56d137ff10a88eb908a1560694c3eb49f09d52d4f04471ca08750d56c83fabc
    name: hmse
    type: application
    urls:
    - hmse-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-04T10:55:28.651502151Z"
