apiVersion: v1
entries:
  hmse:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-06-18T22:03:44.602862196Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 1.2.0
    description: Umbrella chart for running a HMSE workflow
    digest: b6b326f0bea07bdd73dadce66c523aa9d7d7ef189e337355586038beb6e666c4
    name: hmse
    type: application
    urls:
    - hmse-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-06-18T22:03:44.595089019Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 1.0.0
    description: Umbrella chart for running a HMSE workflow
    digest: 0df0cedf797cbb88f07db4242e8e6b2e8576f739cc0d0a390356dcceb5716b6d
    name: hmse
    type: application
    urls:
    - hmse-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2026-06-18T22:03:44.587224805Z"
    dependencies:
    - name: airflow
      repository: https://airflow-helm.github.io/charts
      version: 8.7.0
    - name: hmseWebserver
      repository: file://charts/hmseWebserver
      version: 0.1.0
    description: Umbrella chart for running a HMSE workflow
    digest: a56d137ff10a88eb908a1560694c3eb49f09d52d4f04471ca08750d56c83fabc
    name: hmse
    type: application
    urls:
    - hmse-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-18T22:03:44.57881087Z"
